spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true # 초기화시 data-h2.sql 채우기 위해서 필요한 옵션
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb # db 연결 위한 설정
    #username: sa
    #password: 1234
  sql:
    init:
      data-locations: classpath:data-h2.sql